### ISSUE TITLE
Input data is to small.

### ISSUE THREAD

**Issue by mediaprogramer** [tsurubee/banpei#1]
banpei/banpei/sst.py 50行目
Input data is too small.
がよいかと思われます。

**Comment by walshie4** [comment]
You're passing in data which is smaller than your window value (`w`)

**Comment by tsurubee** [comment]
I am terribly sorry for the late confirmation.
I revised the incorrect comment.
Thank you so much!

**Comment by jessidirk** [comment]
Hi tsurubee! Quick question related to this issue: what is the "window value" and how do you determine what "w" is appropriate for a given dataset?

**Comment by tsurubee** [comment]
Hi, @jessidirk 
"w" means the size of the sliding window.  
In order to know what a sliding window is, it is necessary to understand the anomaly detection method called SST.
The following papers are helpful for understanding. (Please check Figure 2)

https://ide-research.net/papers/2005_SDM_Ide.pdf

And, it is a difficult problem to decide the appropriate "w" because the appropriate value strongly depends on the target time series data.  So, "w" is a hyperparameter that needs to be decided by yourself considering the periodicity of the data.
