### ISSUE TITLE
ERROR: No matching distribution found for banpei

### ISSUE THREAD

**Issue by mnvsekhar** [tsurubee/banpei#10]
pip install banpei is throwing error:

ERROR: Could not find a version that satisfies the requirement banpei (from versions: none)
ERROR: No matching distribution found for banpei

I have been using Python 3.7.4
![2020-07-16](https://user-images.githubusercontent.com/28951777/87680126-08a92980-c74b-11ea-995f-0f63960d8d09.png)

**Comment by tsurubee** [comment]
This error occurs because banpei has not registered with PyPI.
Therefore, the command "pip install banpei" is not valid.
Follow the "Installation" in the README and download banpei to your local environment with "git clone" command.

Thanks to this issue, I started thinking about registering banpei with PyPI! 
Thank you!
