### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement banpei

### ISSUE THREAD

**Issue by kashyapm94** [tsurubee/banpei#11]
I am trying to do `pipenv install banpei` in my virtual env, it is throwing the following error:

```
Installing banpei…
Error:  An error occurred while installing banpei!
Error text: 
ERROR: Could not find a version that satisfies the requirement banpei (from -r /tmp/pipenv-00uw2ca1-requirements/pipenv-x3l4m4in-requirement.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for banpei (from -r /tmp/pipenv-00uw2ca1-requirements/pipenv-x3l4m4in-requirement.txt (line 1))

```

![banpei](https://user-images.githubusercontent.com/35066641/87684315-673dca00-c782-11ea-9152-4a69e20e7c71.png)

**Comment by tsurubee** [comment]
This error occurs because banpei has not registered with PyPI.
Therefore, the command "pip install banpei" is not valid.
Follow the "Installation" in the README and download banpei to your local environment with "git clone" command.

Thanks to this issue, I started thinking about registering banpei with PyPI! 
Thank you!
