### ISSUE TITLE
Citation for banpei

### ISSUE THREAD

**Issue by djoshi5** [tsurubee/banpei#9]
Hello,
I am using banpei for change point detection in my thesis. I would like to cite this work but could not find any citations. It would be great to have Bibtex entry for citation.
Thank You

**Comment by tsurubee** [comment]
Hello,
I am very glad that you use banpei.  
What form of citation are you saying? As far as I know, when I cite OSS on GitHub in papers, I use the following format as Web page.  
```
@webpage{banpei,
  author   = "{H. Tsuruta}",
  title    = "{banpei}",
  url      = {https://github.com/tsurubee/banpei}
}
```
Please let me know if it is not what you want.
Thank You

**Comment by djoshi5** [comment]
That's exactly what I wanted. Thank you!
I also wanted to know whether you could provide me with the theoretical references from which you built this method. I could find couple of journal articles on SST and Lancos method, but could not find anything significant (in terms of scientific research) on hotteling's theory for anomaly detection. Please let me know if you have anything on that.
Again, thank you for all your help.
Stay safe!

**Comment by tsurubee** [comment]
Since I  learned about hotelling's theory from the book, I do not know any research reports of hotelling's theory. (And the book is written in Japanese...)
According to the article below,
https://www.statisticshowto.datasciencecentral.com/hotellings-t-squared/
it seems that [this paper](https://projecteuclid.org/euclid.aoms/1177732979) written in 1931 first mentions about hotelling’s T-Squared.  But, I don't know exactly．
I'm sorry I couldn't be of much help to you.

**Comment by djoshi5** [comment]
Thank you for letting me know. 
I got more than what I was expecting.
Stay safe!
